import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const ctx={window:null,globalThis:null,console,Date,JSON,Map,Set,Number,Array,String,Object,RegExp,Math,performance:{now:()=>0}};ctx.window=ctx;ctx.globalThis=ctx;vm.createContext(ctx);
for(const file of ['site/log-engine.js','site/wazuh-adapter.js','site/log-normalize-fixes.js','site/platform/detection-v3.js','site/platform/detection-pipeline.js'])vm.runInContext(fs.readFileSync(file,'utf8'),ctx,{filename:file});
const sample={_index:'wazuh-alerts-4.x-2026.08.19',_id:'QVjnGaABtebZzq0e6aP8',_source:{agent:{ip:'10.22.42.11',name:'DressariumHostingNEW-SERVER',id:'056'},manager:{name:'itcraft-virtual-machine'},data:{extra_data:'DressariumHostingNEW-SERVER->any'},rule:{mail:true,level:15,description:'Wazuh agent stopped.',groups:['ossec'],mitre:{technique:['Disable or Modify Tools'],id:['T1562.001'],tactic:['Defense Evasion']},id:'506'},location:'wazuh-remoted',decoder:{parent:'ossec',name:'ossec'},id:'1787141023.1848832136',full_log:"ossec: Agent stopped: 'DressariumHostingNEW-SERVER->any'.",timestamp:'2026-08-19T16:03:43.018+0400'}};
const result=ctx.DBMPlatform.detectionPipeline.apply(ctx.DBMLogEngine.analyzeLogs(JSON.stringify(sample)));
assert.equal(result.events.length,1);
const e=result.events[0];
assert.equal(e.eventId,'');
assert.equal(e.host,'DressariumHostingNEW-SERVER');
assert.equal(e.agentIp,'10.22.42.11');
assert.equal(e.wazuhRuleId,'506');
assert.equal(e.wazuhEventFamily,'agent-lifecycle');
assert.equal(e.wazuhLifecycleAction,'stopped');
assert.match(e.message,/Agent stopped/i);
const f=result.findings.find(x=>x.ruleId==='WAZUH-AGENT-STOPPED');
assert.ok(f,'expected WAZUH-AGENT-STOPPED finding');
assert.equal(f.severity,'critical');
assert.ok(f.mitre.includes('T1562.001'));
console.log('Wazuh agent lifecycle regression passed');
